// products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_RESULT = 'GET_PRODUCTS_RESULT';
export const GET_PRODUCT_DETAILS_INIT = 'GET_PRODUCT_DETAILS_INIT';
export const GET_PRODUCT_DETAILS_RESULT = 'GET_PRODUCT_DETAILS_RESULT';
export const GET_PRODUCT_DETAILS_LOADING = 'GET_PRODUCT_DETAILS_LOADING';
export const ADD_PRODUCT_TO_SHOPING_CART_INIT = 'ADD_PRODUCT_TO_SHOPING_CART_INIT';
export const ADD_PRODUCT_TO_SHOPING_CART = 'ADD_PRODUCT_TO_SHOPING_CART';
export const MARK_PRODUCT_AS_IN_SHOPING_CART = 'MARK_PRODUCT_AS_IN_SHOPING_CART';
export const LOAD_SHOPING_CART_FROM_LOCAL_STORAGE_INIT = 'LOAD_SHOPING_CART_FROM_LOCAL_STORAGE_INIT';
export const LOAD_SHOPING_CART_FROM_LOCAL_STORAGE = 'LOAD_SHOPING_CART_FROM_LOCAL_STORAGE';
export const REMOVE_PRODUCT_FROM_SHOPING_CART_INIT = 'REMOVE_PRODUCT_FROM_SHOPING_CART_INIT';

// errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
