// products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_RESULT = 'GET_PRODUCTS_RESULT';
export const GET_PRODUCT_DETAILS_INIT = 'GET_PRODUCT_DETAILS_INIT';
export const GET_PRODUCT_DETAILS_RESULT = 'GET_PRODUCT_DETAILS_RESULT';
export const GET_PRODUCT_DETAILS_LOADING = 'GET_PRODUCT_DETAILS_LOADING';

// errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
